module.exports = {
    CONNECTION_STRING : 'mongodb://localhost:27017/booksharedb',
    BOOKS_PER_PAGE : 15,
    COMMENTS_PER_PAGE : 20,
    HOST: 'http://localhost:8888',
    INIT_CATEGORIES : [
        { type : 'Arts & Music'},
        { type : 'Biographies'},
        { type : 'Business'},
        { type : 'Comics'},
        { type : 'Computer & Tech'},
        { type : 'Cooking'},
        { type : 'Edu & Referance'},
        { type : 'Entertainment'},
        { type : 'Gay & Lesbian'},
        { type : 'Health & Fitness'},
        { type : 'History'},
        { type : 'Hobbies & Crafts'},
        { type : 'Home & Garden'},
        { type : 'Horror'},
        { type : 'Kids'},
        { type : 'Literature & Fiction'},
        { type : 'Medical'},
        { type : 'Mysteries'},
        { type : 'Parenting'},
        { type : 'Religion'},
        { type : 'Romance'},
        { type : 'Science & Math'},
        { type : 'Self-Help'},
        { type : 'Social Sciences'},
        { type : 'Sports'},
        { type : 'Teen'},
        { type : 'Travel'}
    ]
};