module.exports = {
    CONNECTION_STRING: 'mongodb://localhost:27017/booksharedb',
    BOOKS_PER_PAGE: 15,
    COMMENTS_PER_PAGE: 5,
    HOST: 'http://localhost:8888',
    INIT_CATEGORIES: [
        { name: 'Arts & Music' },
        { name: 'Biographies' },
        { name: 'Business' },
        { name: 'Comics' },
        { name: 'Computer & Tech' },
        { name: 'Cooking' },
        { name: 'Edu & Referance' },
        { name: 'Entertainment' },
        { name: 'Gay & Lesbian' },
        { name: 'Health & Fitness' },
        { name: 'History' },
        { name: 'Hobbies & Crafts' },
        { name: 'Home & Garden' },
        { name: 'Horror' },
        { name: 'Kids' },
        { name: 'Literature & Fiction' },
        { name: 'Medical' },
        { name: 'Mysteries' },
        { name: 'Parenting' },
        { name: 'Religion' },
        { name: 'Romance' },
        { name: 'Science & Math' },
        { name: 'Self-Help' },
        { name: 'Social Sciences' },
        { name: 'Sports' },
        { name: 'Teen' },
        { name: 'Travel' }
    ]
};